### ISSUE TITLE
How to take whole page screenshot in node-server-screenshot

### ISSUE THREAD

**Issue by pavithra-01** [legraphista/node-server-screenshot#11]
In, this, There is no option to set window size and shot size. So It only captures the visibility part of the window.

**Comment by legraphista** [comment]
Hi @pavithra-01 
There is no way unfortunately to set the shot size as different from the windows size.
That being said, i've just published `0.2.2` to allow you to set the `width` and `height` higher than your screen size as long as the option `show` is set to `false`

**Comment by legraphista** [comment]
As an example, here's https://en.wikipedia.org/wiki/List_of_social_networking_websites at 1280x17000

<details>
<summary> Very long image </summary>
<br/>

![test](https://user-images.githubusercontent.com/962643/64157637-b6fff500-ce3f-11e9-9a65-81b41218b597.png)
</details>

**Comment by pavithra-01** [comment]
Kindly share the  code for the above wikipedia example

**Comment by pavithra-01** [comment]
At the same time, These codes are working fine in local. But it doesn't work on live server. Why ?

**Comment by legraphista** [comment]
> Kindly share the code for the above wikipedia example

```javascript
var app = require("./index");
app.fromURL(
  'https://en.wikipedia.org/wiki/List_of_social_networking_websites',
  'test.png', 
  {width: 1280, height: 17000, show: false}, 
  (e) => e ? console.error(e) : console.log('done')
);
```

> At the same time, These codes are working fine in local. But it doesn't work on live server. Why ?

My quess is that you are running in a headless linux environment; If my guess is correct, follow these steps: https://github.com/legraphista/node-server-screenshot/issues/10#issuecomment-514588414

**Comment by pavithra-01** [comment]
![test](https://user-images.githubusercontent.com/54837070/64161903-08b67880-ce5c-11e9-829c-262447165aaf.png)

I test the above code. It generates image like above.

**Comment by legraphista** [comment]
Are you running version `0.2.2`?

**Comment by pavithra-01** [comment]
Sry. I used the 0.2.1 version. Now Updated.But it generates image like below
![test](https://user-images.githubusercontent.com/54837070/64165677-26d3a700-ce63-11e9-92b8-80fadeda49d3.png)

**Comment by pavithra-01** [comment]
It generates the blank transparent image
