### ISSUE TITLE
Png not working

### ISSUE THREAD

**Issue by rickerd** [legraphista/node-server-screenshot#20]
Great library but I don't get the png feature to work.

Am I missing something? The docs says if you set the path to `null` it would give a stream in png in the second callback parameter but it gives errors.

```
let result = 'svg string is this normally';
const screenShotOptions = {
                show: false,
            };
screenshotservice.fromHTML(result, '', screenShotOptions, (err, data) => {
                    console.log(data);
                    res.set('Content-Type', 'image/png');
                    res.send('data');
                });
```

**Comment by legraphista** [comment]
Hi @rickerd 
Can you please be more specific on the errors you encountered? 
The example code you provided does log a buffer, and saving the buffer to a file does render a valid PNG.

**Comment by rickerd** [comment]
That is so weird! It doesn't work on my side.
Your reply is quick tho! But i've changed to another library that just makes a svg string to png and outputs it as a buffer that is served to the browser.

Thanks anyway! Your lib is great.

**Comment by legraphista** [comment]
No problem! 
This module uses electron which is a bit overkill anyways if you just want to render a SVG to a PNG :joy:
