### ISSUE TITLE
No buffer when clipping image

### ISSUE THREAD

**Issue by FabioBannerwise** [legraphista/node-server-screenshot#6]
It's not creating a buffer when I clip an image.

```
      screenshot.fromHTML(myHTML, null, {
        clip: {
          x: 0,
          y: 0,
          width: 300,
          height: 250
        }
      }, function(error: any, buffer: any) {
        console.log(error, buffer);
      });
```

**Comment by legraphista** [comment]
Hi! Thanks for the bug report! I've fixed the issue in https://github.com/legraphista/node-server-screenshot/commit/12546d45335f215d4d05f65360bdf050ae4fa78c.
Please feel free to update to `0.2.1` and report if the issue persists.

**Comment by FabioBannerwise** [comment]
Fixed!
Thank you :)

**Comment by legraphista** [comment]
With pleasure! 😃
