### ISSUE TITLE
Image has double the indicated size

### ISSUE THREAD

**Issue by FabioBannerwise** [legraphista/node-server-screenshot#7]
As the title suggests, if I clip an image with 300x250 size, it will output a file 600x500.

**Comment by legraphista** [comment]
Hi! Thanks for the bug report! I've fixed the issue in https://github.com/legraphista/node-server-screenshot/commit/a08aa288accafde3b389f0ef264aaafe77111376.
Please feel free to update to `0.2.1` and report if the issue persists.

**Comment by FabioBannerwise** [comment]
Fixed!
Thank you :)

**Comment by legraphista** [comment]
With pleasure! 😃
