### ISSUE TITLE
Quality/resolution?

### ISSUE THREAD

**Issue by brandondurham** [legraphista/node-server-screenshot#8]
Thanks so much for putting this together! Really nice little tool. I was wondering, is it possible to set a quality or “resolution” for the image?

**Comment by legraphista** [comment]
Hi @brandondurham, thanks for asking.
Yes, you can pass an object with properties where you can set `width` and `height` in pixels. You can also set `scale` to achieve a more granular image, but keep in mind that width and height are multiplied by scale. For example, if you set a resolution of 500x500 at scale 2, you will end up with an image of 1000x1000 pixels.

**Comment by brandondurham** [comment]
Perfect. Thank you!

**Comment by legraphista** [comment]
Here's an example where the callback receivers the PNG encoded image buffer.
```
app.fromURL(
   "https://google.com", 
   null, 
   {
      clip: { x: 490, y: 180, width: 100, height: 100 }, 
      scale: 5,
      width: 1280,
      height: 720
   }, 
   callback
);
```

**Comment by kwiser** [comment]
long page resolution not good. Some css not working in capture.

website: https://artoonsolutions.com/

screenshot taken by this plugin:

![artoonsolutions](https://user-images.githubusercontent.com/56244954/71816164-c326e800-30a7-11ea-880c-48f9fe56e7e6.png)
